var keyMirror = require('keymirror');

// Define action constants
module.exports = keyMirror({
  RECEIVE_VENDORS_RES: null,
  RECEIVE_ORGNAIZATION_RES:null,
  RECEIVE_V_BUYERS_RES:null,
  RECEIVE_VENDOR_COUNT_RES:null,
  RECEIVE_B_VRNDORS_RES:null,
  RECEIVE_REMIT_INFO_RES:null,
  RECEIVE_BUYER_COUNT_RES:null,
  RECEIVE_REMIT_INFO_RES:null,
  RECEIVE_USERS_ORGS_COUNTS_RES:null,
  RECEIVE_ALL_ORGNAIZATIONS_RES:null,
  RECEIVE_ALL_USERS_RES:null,
  RECEIVE_ALL_PENDING: null,
  RECEIVE_ORGNAIZATION_RES:null,
  RECEIVE_USER_BY_ORGID_RES:null
});